# Generated by Django 5.1.5 on 2025-01-28 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('resume', models.FileField(blank=True, null=True, upload_to='job_seekers/resumes/')),
                ('skills', models.TextField()),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=600)),
                ('education', models.CharField(max_length=600)),
                ('experiences', models.CharField(max_length=600)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
